
# dkr387php

version: '3.6'

services:

  web:
    #image: php:7.2.2-apache
    build: ./php
    # image: dkr378php8
    # container_name: dkr378php8
    restart: always
    # depends_on:
      # - db
    env_file:
      - ../.env
    volumes:
      - ../html/:/var/www/html/
           
    ports:
      - "6092:80"
    stdin_open: true
    tty: true
    networks:
      - one
    
    
  # db:
    # image: mysql
    # # build: ./mysql
    # # image: dkr378php8mysq
    # # container_name: dkr378php8mysq
    # restart: always
    # env_file:
      # - env
    # # environment:
      # # MYSQL_ROOT_PASSWORD: root
      # # MYSQL_DATABASE: test
      # # MYSQL_USER: dev
      # # MYSQL_PASSWORD: dev
    # # ports:
      # # - "6022:3306"
    # volumes:
      # - ../data/mysql387php/:/var/lib/mysql/
    # networks:
      # - one

      
networks:
  one:
    name: one
      external:true
    